<?php

echo SHOWVLAN
IPCONFIG/ALL 
SUBNETTING
ACK
SUDO SU
BERNAAAAAAAAAT
TO FASI
CAFELASO DE ARVELLANA
SCRIDELINU
EL MIGUE DE AERONAUTICA
LA CHUPAS TO FUERTE
JI O KKKKKKKKK
LO VA A ASE TU PRIMA
TELA DE FASI
TELA DE GRASIOSO
CROMOSOMA DE MAS
JEZUUUUUuUUu
BIGGGGGGGGGGGG KEEEEEEEEEEEEEERRRRRY
PAAAAAACO
PACO MACACO
NINO CANINO
MIGUEL PAJERO
MIGUEL PAJAS
TIMAGINA
UNA COSA TE VIA DESI
NO ME ESTAS ENTENDIENDO
AU AU AU 
ER CAPI Y ER MANULE
LA PAGUITA (BMW)
MÁNUEL FLÓRIDO
ERES UN HIPOCRITA
ERES UN CAPULLO
ÁDAM
BERNAAAAAAAAAT
BIBIBIBIBIBIIIIIIIIIIIIIG KEEEEERRRY
KERRY KERRY KERRY KERRY KERRY KERRY
PROESOOOOOOO
EL CAPI VA A SACA UN 10 EN BASE DE DATO
EL QUE NO SAQUE UN 10 ES GILIPOLLA
Q HACE JOSE ANGEL DE MODERADOR
KERRY LA MASCARILLA
IVAN Y VENIAN
EL MIGUE SIN MINUSVALIA
el gonzalo sin papeles
el capi sin paguita
el kerry sin follarse a menores
YA OS TOCARA A USTEDES HACER VIDEOLLAMADAS EN CASA
POR LO MENOS NO ME FOLLO A MENORES
CHIN WAN YAAAAAAA TAMAGOCHI
BERNAAAAAAAAAAT; ESE SOY YO!
chicooooooooooooooos, me escuchais?
tiene hora? me la chupa?
periquito pin pin
arp -a
te voy a demandar
caaaaaaaaaapiiiiiiiiiitan de navio
lactovit
ZULEPO
CREATE OR REPLACE PROCEDURE
SET SERVER OUTPUT ON
manulin manulen
miguelin miguelon
migue chocate con la pared
el migue sin sangre en la polla
el migue duchandose
q bonito es al salir de casa(8)
docker-cooooooooooompoooouus
DHCP
ji, tu padre
eres un disminuido
ji, tela
miguel wonker
innachio
disminuido
tupac
tu padre el tuerto
mail:to


?>